### ISSUE TITLE
RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.posts.Posts...

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#11966]
Sentry merged some unrelated issues to this crash, so the numbers are misleading. Unfortunately I can't figure out a way to separate these issues, so we'll just need to fix this one and resolve it so the new crashes will be separated. The good thing is, we already have similar crashes to the merged ones in a separate issue, so we are aware of them, and this crash seems pretty straightforward since we know exactly where it's happening.

@yaelirub Jirka might be a good candidate for this crash.

**Sentry Url**: https://sentry.io/share/issue/331cfd8602f44704b34394279ba634a5/
**User Count**: 376
**Count**: 9379
**First Release**: org.wordpress.android-12.3-rc-2
**First Seen**: 2019-05-06T16:14:34Z
**Last Seen**: 2020-05-20T17:21:58Z
**24 Hours**: 7
**30 Days**: 329

```
RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.posts.PostsListActivity}: kotlin.TypeCastException: null cannot be cast to non-null type org.wordpress.android.fluxc.model.SiteModel
     at org.wordpress.android.ui.posts.PostsListActivity.onCreate(PostsListActivity.kt:143)
     at android.app.Activity.performCreate(Activity.java:7258)
     at android.app.Activity.performCreate(Activity.java:7249)
     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1222)
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3059)
     at android.app.ActivityThread.-wrap11(null:0)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1724)
     at android.os.Handler.dispatchMessage(Handler.java:106)
     at android.os.Looper.loop(Looper.java:164)
...
(4 additional frame(s) were not displayed)
```

**Comment by yaelirub** [comment]
Thank you, @oguzkocer ! @malinajirka , can you please follow the proposed plan of action  in Oguz [comment](https://github.com/wordpress-mobile/WordPress-Android/issues/9905#issuecomment-631694788) ?

We assume this is low priority  but since the numbers in that crash are unclear and unrelated crashes are merged into it we can't tell.

**Comment by malinajirka** [comment]
Hmm, I've looked into this issue and I didn't find any path which might result in this exception 🤷. It seems all the paths were fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/10826. 


>we'll just need to fix this one and resolve it so the new crashes will be separated

Btw, would this plan work? If we mark it as resolved and the issue (or another issue in this ticket) happens again, Sentry will just re-open the original issue, right?

**Comment by oguzkocer** [comment]
@malinajirka I don't think that's correct. The crash can still happen if the `PendingIntent` generated for the notifications have a `null` `SiteModel` or if the extras for the intent are cleared. I've tried a few things to reproduce the issue, but couldn't find reproducible steps yet. From the logs in Sentry, I can see that it happens for both successful and error notifications for post upload. It looks like similar issues do happen in other places as well, not just Post list activity. A common action before the crash is to put the app in the background, which I think is necessary for the notification to even show up, but it looks like the app is brought back to foreground before the crash happens. There are cases in which the `PendingIntent` may have its extras cleared as discussed in this StackOverflow thread (probably not limited to it): https://stackoverflow.com/questions/18037991/pendingintent-does-not-send-intent-extras, but I don't know if it's applicable in our situation.

Unfortunately I can't sink too much more time into this, but I hope this will serve as a good starting point since at least we have an idea of what to look for.

> Btw, would this plan work? If we mark it as resolved and the issue (or another issue in this ticket) happens again, Sentry will just re-open the original issue, right?

I am hoping not. If that's the case we'll have at least correct stacktraces for the last events, so it'll be easier to address. The more I look at this issue, the more confused I get. It looks like it's reporting so many different issues, so I don't know why they are all grouped. I thought I made a mistake while cleaning up some other crashes, but I don't see it in the merged issues tab either. 🤷‍♂️

**Comment by malinajirka** [comment]
> The crash can still happen if the PendingIntent generated for the notifications have a null SiteModel

I believe it can't be null as the parameter is marked as `nonnull` and it's accessed before - so it'd have crashed on NPE.

>if the extras for the intent are cleared

If it can really happen it's a bug of the OS. But tbh I don't believe it can happen as it'd be a very known issue.

>I don't think that's correct.
>It looks like similar issues do happen in other places as well, not just Post list activity. 

I didn't say we don't have a bug. I just said that I haven't found any path which might lead to the exception. I think we somewhere delete the extras and the fragment crashes after configuration change as the extras are not there anymore. But I haven't found anything.

>I am hoping not. If that's the case we'll have at least correct stacktraces for the last events, so it'll be easier to address.

From my experience that's what will happen. But I agree that we'll be able to look into the most recent stacktraces.


Imo it's not worth spending more time on this particular crash unless we have more info about it (especially steps for reproduction).

**Comment by oguzkocer** [comment]
> I believe it can't be null as the parameter is marked as nonnull and it's accessed before - so it'd have crashed on NPE.

Nullability annotations such as `@NonNull` are just markers. For example, they don't prevent a null value being passed as an argument to a `@NonNull` parameter. You can test this with the following diff: 

```
diff --git a/WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java b/WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java
index ff9f5da353..ea94350684 100644
--- a/WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java
+++ b/WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java
@@ -205,6 +205,11 @@ public class MySiteFragment extends Fragment implements
             mIsDomainCreditAvailable = savedInstanceState.getBoolean(KEY_IS_DOMAIN_CREDIT_AVAILABLE, false);
             mIsDomainCreditChecked = savedInstanceState.getBoolean(KEY_DOMAIN_CREDIT_CHECKED, false);
         }
+        someMethod(null);
+    }
+
+    private void someMethod(@NonNull String someValue) {
+        AppLog.i(T.MAIN, "some value is: " + someValue);
     }
 
     private void refreshMeGravatar() {
```

The notification generation can be done with a null value and this will make the app crash, I've verified that before I submitted my previous comment. Having said that, I wasn't able to find a specific scenario either.

**Comment by malinajirka** [comment]
>Nullability annotations such as @NonNull are just markers. 

Yeah, I agree. The comment didn't make sense - the important bit was "it's accessed before". But even that is true only for the "success" path. The error path can theoretically be called with "null" - however, I've checked all the paths yesterday and they all seem correct. Thanks for the elaboration though;)!

**Comment by designsimply** [comment]
Graph to watch (even with the merged events we can look for trends going forward): [90d graph for Sentry issue 1014087625](https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1014087625&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29).

**Comment by malinajirka** [comment]
I went over the last +- 100 recorded events. +- 15 of these events were related to the `PostsListActivity`. I investigated these events and I noticed an interesting thing.
All of the events crash on Samsung devices - SM-G610M, SM-G610F, SM-G615F, SM-J710F. Moreover, all of these devices run Android 8.1.0. Therefore I think it's ok to assume this is a bug in the Samsung's ROM - Android 8.1.0. 

I think the next step would be to try to find someone who has one of these devices and try to reproduce the crash there.

**Comment by designsimply** [comment]
**Events in the last 90d:** 9,800
**Users affected in the last 90d:** 398
**Culprit:** `android.app.ActivityThread in performLaunchActivity`
**Note:** 85% of the recorded crashes in the last 90 were on Android 8.1.0
<sub>WORDPRESS-ANDROID-W: https://sentry.io/share/issue/331cfd8602f44704b34394279ba634a5/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1014087625&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/85910808-3818e600-b7de-11ea-9e16-7b9706d11783.png)</a>

**Comment by designsimply** [comment]
A search for "Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.posts.PostsListActivity}: kotlin.TypeCastException: null cannot be cast to non-null type org.wordpress.android.fluxc.model.SiteModel" in Sentry Discover shows this result:

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=%22Unable+to+start+activity+ComponentInfo%7Borg.wordpress.android%2Forg.wordpress.android.ui.posts.PostsListActivity%7D%3A+kotlin.TypeCastException%3A+null+cannot+be+cast+to+non-null+type+org.wordpress.android.fluxc.model.SiteModel%22&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/90825774-a4075e80-e2f6-11ea-9d64-5a46ab1197cf.png)</a>

88% of the recorded crashes in the [WORDPRESS-ANDROID-W](https://sentry.io/share/issue/331cfd8602f44704b34394279ba634a5/) Sentry issue, which contains the error noted above, are for Android 8.1.0.

I looked at the breadcrumbs for the latest 10 events in this issue today and noticed that some of the crashes seem to happen while on the Posts List screen after a post with a failed image upload has happened in the past. Can someone help me double check this to see if they spot a similar trend?

Noting that we're looking for someone with a Samsung device running Android 8.1.0 to help test this.

**Comment by designsimply** [comment]
A search for `"Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.posts.PostsListActivity}: kotlin.TypeCastException: null cannot be cast to non-null type org.wordpress.android.fluxc.model.SiteModel"` in Sentry Discover shows this result:

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=%22Unable+to+start+activity+ComponentInfo%7Borg.wordpress.android%2Forg.wordpress.android.ui.posts.PostsListActivity%7D%3A+kotlin.TypeCastException%3A+null+cannot+be+cast+to+non-null+type+org.wordpress.android.fluxc.model.SiteModel%22&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/96305848-cbf40500-0fbb-11eb-935e-1b891e97a552.png)</a>

**Comment by designsimply** [comment]
A search for `"Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.posts.PostsListActivity}: kotlin.TypeCastException: null cannot be cast to non-null type org.wordpress.android.fluxc.model.SiteModel"` in Sentry Discover shows this result:

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=%22Unable+to+start+activity+ComponentInfo%7Borg.wordpress.android%2Forg.wordpress.android.ui.posts.PostsListActivity%7D%3A+kotlin.TypeCastException%3A+null+cannot+be+cast+to+non-null+type+org.wordpress.android.fluxc.model.SiteModel%22&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/100304409-e971a280-2f5b-11eb-99b0-bb8218d42fcf.png)</a>

Noticed a slight downward trend overall and that there were only 2 events showing for the latest release (16.1 released 10d ago).

**Comment by designsimply** [comment]
A search for `"Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.posts.PostsListActivity}: kotlin.TypeCastException: null cannot be cast to non-null type org.wordpress.android.fluxc.model.SiteModel"` in Sentry Discover returns 469 events in the last 90 days:

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=%22Unable+to+start+activity+ComponentInfo%7Borg.wordpress.android%2Forg.wordpress.android.ui.posts.PostsListActivity%7D%3A+kotlin.TypeCastException%3A+null+cannot+be+cast+to+non-null+type+org.wordpress.android.fluxc.model.SiteModel%22&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/105399932-7f831b80-5be1-11eb-9fad-02242954e57a.png)</a>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=version%3A16.4%2A+%22Unable+to+start+activity+ComponentInfo%7Borg.wordpress.android%2Forg.wordpress.android.ui.posts.PostsListActivity%7D%3A+kotlin.TypeCastException%3A+null+cannot+be+cast+to+non-null+type+org.wordpress.android.fluxc.model.SiteModel%22&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/105404989-d986df80-5be7-11eb-9758-0c6cd549588f.png)</a>

This crash appears to be trending down and there were no cases recorded for the latest release which was 16.4 released 10 days ago on Jan 11. Recommend closing.
