### ISSUE TITLE
Editor/Media: image upload failure "Failed to insert media" for a .wepb image on an image block

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#13353]
Steps to reproduce:

1. Long-press to copy the image at the top of this page to copy the .webp file your device (or use your own .webp image). https://images.app.goo.gl/XanTzSj7fbbQjx1aA<br><sup>NOTE: for testing purposes only, image may be subject to copyright.</sup>
1. Go to My Site > + > Blog post.
1. Add a title and and image block.
1. Tap ADD IMAGE > Choose from device.
1. Select the image downloaded in step 1 and tap INSERT.
1. Observe that the image upload fails immediately.

**Result:** when I try to upload a .webp image I downloaded from a Google search into an image block, the media upload fails immediately with an on screen error that says "Failed to insert media. Please tap for options." The logs, however, show a different error that says "MALFORMED_MEDIA_ARG" and "Media upload failed for post 101 : MALFORMED_MEDIA_ARG: media must define a valid MIME type." The Media screen doesn't allow me to select a .webp image at all when I use the media picker there—which would prevent the image upload failure from happening, but the media picker in the editor let's me select a .webp image and then just fails.

```
55 - [Nov-10 22:10 STATS] 🔵 Tracked: media_service_upload_response_error, Properties: {"ext":"webp","age_ms":356745192,"bytes":17682,"mime":"image\/webp","megapixels":0,"error_type":"MALFORMED_MEDIA_ARG"}
56 - [Nov-10 22:10 STATS] 🔵 Tracked: media_service_upload_started, Properties: {"ext":"webp","age_ms":356745198,"bytes":17682,"mime":"image\/webp","megapixels":0}
57 - [Nov-10 22:10 MEDIA] MediaUploadHandler > No more media items to upload. Skipping this request.
58 - [Nov-10 22:10 MEDIA] MediaUploadHandler > Completed
59 - [Nov-10 22:10 MAIN] UploadService > Media upload failed for post 101 : MALFORMED_MEDIA_ARG: media must define a valid MIME type
60 - [Nov-10 22:10 POSTS] updateNotificationErrorForPost: There was an error uploading the media in this post: Media must define a valid MIME type.
61 - [Nov-10 22:10 STATS] 🔵 Tracked: notification_shown, Properties: {"notification_type":"post_upload_error"}
```

Error: "Failed to insert media"|File details seen in Google Photos app|Cannot select same image using Media section
---|---|---
<img src="https://user-images.githubusercontent.com/1119271/98742957-833a2c80-236c-11eb-9034-bf21fd57bda8.png" height="350" alt="failed-to-insert-media">|<img src="https://user-images.githubusercontent.com/1119271/98742953-82a19600-236c-11eb-9fba-aeb64f152882.png" height="350" alt="Screenshot_20201110-154647">|<img src="https://user-images.githubusercontent.com/1119271/98742956-833a2c80-236c-11eb-8385-eaba755ef436.png" height="350" alt="cannot-select-webp-image-from-media-section">

<sup>Tested with WPAndroid 16.1-rc-2 on Pixel 3 Android 11 on a WordPress.com Premium site.</sup>

<details>
<summary>Full set of app logs for this case</summary>

```
WordPress - 16.1-rc-2 - Version code: 949
Android device name: Google Pixel 3

01 - [Nov-10 22:10 API] StackTrace: com.android.volley.ClientError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:199)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

02 - [Nov-10 22:10 API] Dispatching action: PostAction-FETCHED_REVISIONS
03 - [Nov-10 22:10 API] An error occurred while fetching History revisions
04 - [Nov-10 22:10 EDITOR] Hermes is: true
05 - [Nov-10 22:10 EDITOR] Running "gutenberg" with {"initialProps":{"initialData":"","postType":"post","initialHtmlModeEnabled":false,"initialTitle":"","locale":"en-us","translations":{"Strategy":["Strategy"],"Move block down from row %1$s to row %2$s":["Move block down from row %1$s to row %2$s"],"Page title. Empty":["Page title. Empty"],"Paste URL":["Paste URL"],"Choose image or video":["Choose image or video"],"Double tap to open Bottom Sheet with available options":["Double tap to open Bottom Sheet with available options"],"Post title. %s":["Post title. %s"],"Block copied":["Block copied"],"ADD BLOCK HERE":["ADD BLOCK HERE"],"Title:":["Title:"],"Image caption. %s":["Image caption. %s"],"Move block right from position %1$s to position %2$s":["Move block right from position %1$s to position %2$s"],"Move block up":["Move block up"],"Page break block. %s":["Page break block. %s"],"My post publish panel":["My post publish panel"],"An unknown error occurred. Please try again.":["An unknown error occurred. Please try again."],"Double tap to move the block to the right":["Double tap to move the block to the right"],"Template Preview":["Template Preview"],"Choose images":["Choose images"],"Copy block":["Copy block"],"Move block right":["Move block right"],"Updates the title.":["Updates the title."],"Help button":["Help button"],"ADD IMAGE OR VIDEO":["ADD IMAGE OR VIDEO"],"Start writing…":["Start writing…"],"Size":["Size"],"Scrollable block menu closed.":["Scrollable block menu closed."],"Double tap to edit this value":["Double tap to edit this value"],"WordPress Media Library":["WordPress Media Library"],"Want to work with us?":["Want to work with us?"],"Double tap to move the block to the left":["Double tap to move the block to the left"],"Add this email link":["Add this email link"],"Services":["Services"],"Ungroup":["Ungroup"],"Video caption. Empty":["Video caption. Empty"],"Add URL":["Add URL"],"CUSTOMIZE":["CUSTOMIZE"],"Open Block Actions Menu":["Open Block Actions Menu"],"Navigates to customize the gradient":["Navigates to customize the gradient"],"Double tap to redo last change":["Double tap to redo last change"],"Current value is %s":["Current value is %s"],"Reset Block":["Reset Block"],"Here is the panel content!":["Here is the panel content!"],"Double tap to select the option":["Double tap to select the option"],"Edit video":["Edit video"],"Let's talk 👋 Don't hesitate to reach out with the contact information below, or send a message using the form.":["Let's talk 👋 Don't hesitate to reach out with the contact information below, or send a message using the form."],"Add a shortcode…":["Add a shortcode…"],"Tap to hide the keyboard":["Tap to hide the keyboard"],"Add this telephone link":["Add this telephone link"],"Don’t cry because it’s over, smile because it happened.":["Don’t cry because it’s over, smile because it happened."],"Page title. %s":["Page title. %s"],"Double tap to select a video":["Double tap to select a video"],"Add To End":["Add To End"],"(555)555–1234":["(555)555–1234"],"Open Settings":["Open Settings"],"10 Street Road":["10 Street Road"],"Double tap to add a block":["Double tap to add a block"],"Alt Text":["Alt Text"],"Failed to insert media.\nPlease tap for options.":["Failed to insert media.\nPlease tap for options."],"Dr. Seuss":["Dr. Seuss"],"<a href=\"mailto:mail@example.com\">mail@example.com</a>":["<a href=\"mailto:mail@example.com\">mail@example.com</a>"],"Select a color":["Select a color"],"Double tap to select an image":["Double tap to select an image"],"Add annotation":["Add annotation"],"Remove annotations":["Remove annotations"],"Duplicate block":["Duplicate block"],"Tap here to show help":["Tap here to show help"],"Insert mention":["Insert mention"],"Add this link":["Add this link"],"We are a small team of talented professionals with a wide range of skills and experience. We love what we do, and we do it with passion. We look forward to working with you.":["We are a small team of talented professionals with a wide range of skills and experience. We love what we do, and we do it with passion. We look forward to working with you."],"Double tap to go to color settings":["Double tap to go to color settings"],"Team":["Team"],"Blog":["Blog"],"Inspiration":["Inspiration"],"Move block down":["Move block down"],"Take a Photo":["Take a Photo"],"Video caption. %s":["Video caption. %s"],"Show post content":["Show post content"],"What People Say":["What People Say"],"Samuel the Dog":["Samuel the Dog"],"Cut block":["Cut block"],"Move Image Forward":["Move Image Forward"],"Select a layout":["Select a layout"],"Paste block after":["Paste block after"],"Post title. Empty":["Post title. Empty"],"Gallery caption. %s":["Gallery caption. %s"],"Let’s build something together!":["Let’s build something together!"],"Add a description":["Add a description"],"Sally Smith":["Sally Smith"],"%s block. Empty":["%s block. Empty"],"Navigates to custom color picker":["Navigates to custom color picker"],"It is our choices, Harry, that show what we truly are, far more than our abilities.":["It is our choices, Harry, that show what we truly are, far more than our abilities."],"Double tap to toggle setting":["Double tap to toggle setting"],"A short description of the services you offer.":["A short description of the services you offer."],"Replace image or video":["Replace image or video"],"We offer a range of services to help you achieve the results you're after. Not sure what you need, or what it costs? We can explain what services are right for you and tell you more about our fees. Get in touch below.":["We offer a range of services to help you achieve the results you're after. Not sure what you need, or what it costs? We can explain what services are right for you and tell you more about our fees. Get in touch below."],"A short bio with personal history, key achievements, or an interesting fact.":["A short bio with personal history, key achievements, or an interesting fact."],"ADD VIDEO":["ADD VIDEO"],"We are working hard to add more blocks with each release.":["We are working hard to add more blocks with each release."],"Hide keyboard":["Hide keyboard"],"Add To Beginning":["Add To Beginning"],"Replace video":["Replace video"],"Content…":["Content…"],"Block pasted":["Block pasted"],"Take a Video":["Take a Video"],"Edit using web editor":["Edit using web editor"],"Take a Photo or Video":["Take a Photo or Video"],"Only show excerpt":["Only show excerpt"],"Annotations Sidebar":["Annotations Sidebar"],"Double tap to select":["Double tap to select"],"Visitors will want to know who is on the other side of the page. Use this space to write about yourself, your site, your business, or anything you want. Use the testimonials below to quote others, talking about the same thing – in their own words.":["Visitors will want to know who is on the other side of the page. Use this space to write about yourself, your site, your business, or anything you want. Use the testimonials below to quote others, talking about the same thing – in their own words."],"Double tap to select layout":["Double tap to select layout"],"Show section":["Show section"],"Project Name":["Project Name"],"Double tap to move the block down":["Double tap to move the block down"],"USA":["USA"],"Position or Job Title":["Position or Job Title"],"Add paragraph block":["Add paragraph block"],"Scrollable block menu opened. Select a block.":["Scrollable block menu opened. Select a block."],"Block duplicated":["Block duplicated"],"No application can handle this request. Please install a Web browser.":["No application can handle this request. Please install a Web browser."],"Move Image Backward":["Move Image Backward"],"Welcome to our new blog":["Welcome to our new blog"],"ADD IMAGE":["ADD IMAGE"],"This is sample content, included with the template to illustrate its features. Remove or replace it with your own words and media.":["This is sample content, included with the template to illustrate its features. Remove or replace it with your own words and media."],"My pre publish panel":["My pre publish panel"],"Walt Disney":["Walt Disney"],"Portfolio":["Portfolio"],"Gradient Type":["Gradient Type"],"Choose image":["Choose image"],"Choose from device":["Choose from device"],"Select item":["Select item"],"Success Message":["Success Message"],"Move block left from position %1$s to position %2$s":["Move block left from position %1$s to position %2$s"],"A description of the project and the works presented.":["A description of the project and the works presented."],"Sidebar title plugin":["Sidebar title plugin"],"Block removed":["Block removed"],"Let's build something together!":["Let's build something together!"],"Customize Gradient":["Customize Gradient"],"Double tap to open Action Sheet with available options":["Double tap to open Action Sheet with available options"],"Navigate Up":["Navigate Up"],"Block cut":["Block cut"],"Replace Current Block":["Replace Current Block"],"Move block up from row %1$s to row %2$s":["Move block up from row %1$s to row %2$s"],"Move block left":["Move block left"],"Dismiss":["Dismiss"],"'%s' is not fully–supported":["'%s' is not fully–supported"],"Help icon":["Help icon"],"Double tap to undo last change":["Double tap to undo last change"],"Excerpt length (words)":["Excerpt length (words)"],"Translate":["Translate"],"Get in Touch":["Get in Touch"],"Open link in a browser":["Open link in a browser"],"Double tap to change the value using slider":["Double tap to change the value using slider"],"City, 10100":["City, 10100"],"Warning Message":["Warning Message"],"Choose video":["Choose video"],"Problem displaying block":["Problem displaying block"],"%s block options":["%s block options"],"Add Block After":["Add Block After"],"Problem opening the video":["Problem opening the video"],"Copied block":["Copied block"],"Double tap to move the block up":["Double tap to move the block up"],"%s block. This block has invalid content":["%s block. This block has invalid content"],"J.K. Rowling":["J.K. Rowling"],"Block settings":["Block settings"],"The way to get started is to quit talking and begin doing.":["The way to get started is to quit talking and begin doing."],"Link To":["Link To"],"Angle":["Angle"],"Add Block Before":["Add Block Before"],"Search or type URL":["Search or type URL"],"Note: Column layout may vary between themes and screen sizes":["Note: Column layout may vary between themes and screen sizes"],"Try a starter layout":["Try a starter layout"],"%1$s. Current value is %2$s":["%1$s. Current value is %2$s"],"My Document Setting Panel":["My Document Setting Panel"],"My post status info":["My post status info"],"Juan Pérez":["Juan Pérez"],"Email me: <a href=\"mailto:mail@example.com\">mail@example.com</a>":["Email me: <a href=\"mailto:mail@example.com\">mail@example.com</a>"],"My portfolio showcases various projects created throughout my career. See my contact information below and get in touch.":["My portfolio showcases various projects created throughout my career. See my contact information below and get in touch."]},"colors":[{"color":"#cd2653","slug":"accent","name":"Accent Color"},{"color":"#000000","slug":"primary","name":"Primary"},{"color":"#6d6d6d","slug":"secondary","name":"Secondary"},{"color":"#dcd7ca","slug":"subtle-background","name":"Subtle Background"},{"color":"#f5efe0","slug":"background","name":"Background Color"}],"capabilities":{"unsupportedBlockEditor":true,"modalLayoutPicker":true,"mentions":true,"canEnableUnsupportedBlockEditor":true},"editorMode":"editor"},"rootTag":71}
06 - [Nov-10 22:10 EDITOR] 'locale', 'en', { Strategy: [ 'Strategy' ],
  'Move block down from row %1$s to row %2$s': [ 'Move block down from row %1$s to row %2$s' ],
  'Page title. Empty': [ 'Page title. Empty' ],
  'Paste URL': [ 'Paste URL' ],
  'Choose image or video': [ 'Choose image or video' ],
  'Double tap to open Bottom Sheet with available options': [ 'Double tap to open Bottom Sheet with available options' ],
  'Post title. %s': [ 'Post title. %s' ],
  'Block copied': [ 'Block copied' ],
  'ADD BLOCK HERE': [ 'ADD BLOCK HERE' ],
  'Title:': [ 'Title:' ],
  'Image caption. %s': [ 'Image caption. %s' ],
  'Move block right from position %1$s to position %2$s': [ 'Move block right from position %1$s to position %2$s' ],
  'Move block up': [ 'Move block up' ],
  'Page break block. %s': [ 'Page break block. %s' ],
  'My post publish panel': [ 'My post publish panel' ],
  'An unknown error occurred. Please try again.': [ 'An unknown error occurred. Please try again.' ],
  'Double tap to move the block to the right': [ 'Double tap to move the block to the right' ],
  'Template Preview': [ 'Template Preview' ],
  'Choose images': [ 'Choose images' ],
  'Copy block': [ 'Copy block' ],
  'Move block right': [ 'Move block right' ],
  'Updates the title.': [ 'Updates the title.' ],
  'Help button': [ 'Help button' ],
  'ADD IMAGE OR VIDEO': [ 'ADD IMAGE OR VIDEO' ],
  'Start writing…': [ 'Start writing…' ],
  Size: [ 'Size' ],
  'Scrollable block menu closed.': [ 'Scrollable block menu closed.' ],
  'Double tap to edit this value': [ 'Double tap to edit this value' ],
  'WordPress Media Library': [ 'WordPress Media Library' ],
  'Want to work with us?': [ 'Want to work with us?' ],
  'Double tap to move the block to the left': [ 'Double tap to move the block to the left' ],
  'Add this email link': [ 'Add this email link' ],
  Services: [ 'Services' ],
  Ungroup: [ 'Ungroup' ],
  'Video caption. Empty': [ 'Video caption. Empty' ],
  'Add URL': [ 'Add URL' ],
  CUSTOMIZE: [ 'CUSTOMIZE' ],
  'Open Block Actions Menu': [ 'Open Block Actions Menu' ],
  'Navigates to customize the gradient': [ 'Navigates to customize the gradient' ],
  'Double tap to redo last change': [ 'Double tap to redo last change' ],
  'Current value is %s': [ 'Current value is %s' ],
  'Reset Block': [ 'Reset Block' ],
  'Here is the panel content!': [ 'Here is the panel content!' ],
  'Double tap to select the option': [ 'Double tap to select the option' ],
  'Edit video': [ 'Edit video' ],
  'Let\'s talk 👋 Don\'t hesitate to reach out with the contact information below, or send a message using the form.': [ 'Let\'s talk 👋 Don\'t hesitate to reach out with the contact information below, or send a message using the form.' ],
  'Add a shortcode…': [ 'Add a shortcode…' ],
  'Tap to hide the keyboard': [ 'Tap to hide the keyboard' ],
  'Add this telephone link': [ 'Add this telephone link' ],
  'Don’t cry because it’s over, smile because it happened.': [ 'Don’t cry because it’s over, smile because it happened.' ],
  'Page title. %s': [ 'Page title. %s' ],
  'Double tap to select a video': [ 'Double tap to select a video' ],
  'Add To End': [ 'Add To End' ],
  '(555)555–1234': [ '(555)555–1234' ],
  'Open Settings': [ 'Open Settings' ],
  '10 Street Road': [ '10 Street Road' ],
  'Double tap to add a block': [ 'Double tap to add a block' ],
  'Alt Text': [ 'Alt Text' ],
  'Failed to insert media.\nPlease tap for options.': [ 'Failed to insert media.\nPlease tap for options.' ],
  'Dr. Seuss': [ 'Dr. Seuss' ],
  '<a href="mailto:mail@example.com">mail@example.com</a>': [ '<a href="mailto:mail@example.com">mail@example.com</a>' ],
  'Select a color': [ 'Select a color' ],
  'Double tap to select an image': [ 'Double tap to select an image' ],
  'Add annotation': [ 'Add annotation' ],
  'Remove annotations': [ 'Remove annotations' ],
  'Duplicate block': [ 'Duplicate block' ],
  'Tap here to show help': [ 'Tap here to show help' ],
  'Insert mention': [ 'Insert mention' ],
  'Add this link': [ 'Add this link' ],
  'We are a small team of talented professionals with a wide range of skills and experience. We love what we do, and we do it with passion. We look forward to working with you.': [ 'We are a small team of talented professionals with a wide range of skills and experience. We love what we do, and we do it with passion. We look forward to working with you.' ],
  'Double tap to go to color settings': [ 'Double tap to go to color settings' ],
  Team: [ 'Team' ],
  Blog: [ 'Blog' ],
  Inspiration: [ 'Inspiration' ],
  'Move block down': [ 'Move block down' ],
  'Take a Photo': [ 'Take a Photo' ],
  'Video caption. %s': [ 'Video caption. %s' ],
  'Show post content': [ 'Show post content' ],
  'What People Say': [ 'What People Say' ],
  'Samuel the Dog': [ 'Samuel the Dog' ],
  'Cut block': [ 'Cut block' ],
  'Move Image Forward': [ 'Move Image Forward' ],
  'Select a layout': [ 'Select a layout' ],
  'Paste block after': [ 'Paste block after' ],
  'Post title. Empty': [ 'Post title. Empty' ],
  'Gallery caption. %s': [ 'Gallery caption. %s' ],
  'Let’s build something together!': [ 'Let’s build something together!' ],
  'Add a description': [ 'Add a description' ],
  'Sally Smith': [ 'Sally Smith' ],
  '%s block. Empty': [ '%s block. Empty' ],
  'Navigates to custom color picker': [ 'Navigates to custom color picker' ],
  'It is our choices, Harry, that show what we truly are, far more than our abilities.': [ 'It is our choices, Harry, that show what we truly are, far more than our abilities.' ],
  'Double tap to toggle setting': [ 'Double tap to toggle setting' ],
  'A short description of the services you offer.': [ 'A short description of the services you offer.' ],
  'Replace image or video': [ 'Replace image or video' ],
  'We offer a range of services to help you achieve the results you\'re after. Not sure what you need, or what it costs? We can explain what services are right for you and tell you more about our fees. Get in touch below.': [ 'We offer a range of services to help you achieve the results you\'re after. Not sure what you need, or what it costs? We can explain what services are right for you and tell you more about our fees. Get in touch below.' ],
  'A short bio with personal history, key achievements, or an interesting fact.': [ 'A short bio with personal history, key achievements, or an interesting fact.' ],
  'ADD VIDEO': [ 'ADD VIDEO' ],
  'We are working hard to add more blocks with each release.': [ 'We are working hard to add more blocks with each release.' ],
  'Hide keyboard': [ [TOO BIG formatValueCalls 201 exceeded limit of 200] ],
  'Add To Beginning': [TOO BIG formatValueCalls 202 exceeded limit of 200],
  'Replace video': [TOO BIG formatValueCalls 203 exceeded limit of 200],
  'Content…': [TOO BIG formatValueCalls 204 exceeded limit of 200],
  'Block pasted': [TOO BIG formatValueCalls 205 exceeded limit of 200],
  'Take a Video': [TOO BIG formatValueCalls 206 exceeded limit of 200],
  'Edit using web editor': [TOO BIG formatValueCalls 207 exceeded limit of 200],
  'Take a Photo or Video': [TOO BIG formatValueCalls 208 exceeded limit of 200],
  'Only show excerpt': [TOO BIG formatValueCalls 209 exceeded limit of 200],
  'Annotations Sidebar': [TOO BIG formatValueCalls 210 exceeded limit of 200],
  'Double tap to select': [TOO BIG formatValueCalls 211 exceeded limit of 200],
  'Visitors will want to know who is on the other side of the page. Use this space to write about yourself, your site, your business, or anything you want. Use the testimonials below to quote others, talking about the same thing – in their own words.': [TOO BIG formatValueCalls 212 exceeded limit of 200],
  'Double tap to select layout': [TOO BIG formatValueCalls 213 exceeded limit of 200],
  'Show section': [TOO BIG formatValueCalls 214 exceeded limit of 200],
  'Project Name': [TOO BIG formatValueCalls 215 exceeded limit of 200],
  'Double tap to move the block down': [TOO BIG formatValueCalls 216 exceeded limit of 200],
  USA: [TOO BIG formatValueCalls 217 exceeded limit of 200],
  'Position or Job Title': [TOO BIG formatValueCalls 218 exceeded limit of 200],
  'Add paragraph block': [TOO BIG formatValueCalls 219 exceeded limit of 200],
  'Scrollable block menu opened. Select a block.': [TOO BIG formatValueCalls 220 exceeded limit of 200],
  'Block duplicated': [TOO BIG formatValueCalls 221 exceeded limit of 200],
  'No application can handle this request. Please install a Web browser.': [TOO BIG formatValueCalls 222 exceeded limit of 200],
  'Move Image Backward': [TOO BIG formatValueCalls 223 exceeded limit of 200],
  'Welcome to our new blog': [TOO BIG formatValueCalls 224 exceeded limit of 200],
  'ADD IMAGE': [TOO BIG formatValueCalls 225 exceeded limit of 200],
  'This is sample content, included with the template to illustrate its features. Remove or replace it with your own words and media.': [TOO BIG formatValueCalls 226 exceeded limit of 200],
  'My pre publish panel': [TOO BIG formatValueCalls 227 exceeded limit of 200],
  'Walt Disney': [TOO BIG formatValueCalls 228 exceeded limit of 200],
  Portfolio: [TOO BIG formatValueCalls 229 exceeded limit of 200],
  'Gradient Type': [TOO BIG formatValueCalls 230 exceeded limit of 200],
  'Choose image': [TOO BIG formatValueCalls 231 exceeded limit of 200],
  'Choose from device': [TOO BIG formatValueCalls 232 exceeded limit of 200],
  'Select item': [TOO BIG formatValueCalls 233 exceeded limit of 200],
  'Success Message': [TOO BIG formatValueCalls 234 exceeded limit of 200],
  'Move block left from position %1$s to position %2$s': [TOO BIG formatValueCalls 235 exceeded limit of 200],
  'A description of the project and the works presented.': [TOO BIG formatValueCalls 236 exceeded limit of 200],
  'Sidebar title plugin': [TOO BIG formatValueCalls 237 exceeded limit of 200],
  'Block removed': [TOO BIG formatValueCalls 238 exceeded limit of 200],
  'Let\'s build something together!': [TOO BIG formatValueCalls 239 exceeded limit of 200],
  'Customize Gradient': [TOO BIG formatValueCalls 240 exceeded limit of 200],
  'Double tap to open Action Sheet with available options': [TOO BIG formatValueCalls 241 exceeded limit of 200],
  'Navigate Up': [TOO BIG formatValueCalls 242 exceeded limit of 200],
  'Block cut': [TOO BIG formatValueCalls 243 exceeded limit of 200],
  'Replace Current Block': [TOO BIG formatValueCalls 244 exceeded limit of 200],
  'Move block up from row %1$s to row %2$s': [TOO BIG formatValueCalls 245 exceeded limit of 200],
  'Move block left': [TOO BIG formatValueCalls 246 exceeded limit of 200],
  Dismiss: [TOO BIG formatValueCalls 247 exceeded limit of 200],
  '\'%s\' is not fully–supported': [TOO BIG formatValueCalls 248 exceeded limit of 200],
  'Help icon': [TOO BIG formatValueCalls 249 exceeded limit of 200],
  'Double tap to undo last change': [TOO BIG formatValueCalls 250 exceeded limit of 200],
  'Excerpt length (words)': [TOO BIG formatValueCalls 251 exceeded limit of 200],
  Translate: [TOO BIG formatValueCalls 252 exceeded limit of 200],
  'Get in Touch': [TOO BIG formatValueCalls 253 exceeded limit of 200],
  'Open link in a browser': [TOO BIG formatValueCalls 254 exceeded limit of 200],
  'Double tap to change the value using slider': [TOO BIG formatValueCalls 255 exceeded limit of 200],
  'City, 10100': [TOO BIG formatValueCalls 256 exceeded limit of 200],
  'Warning Message': [TOO BIG formatValueCalls 257 exceeded limit of 200],
  'Choose video': [TOO BIG formatValueCalls 258 exceeded limit of 200],
  'Problem displaying block': [TOO BIG formatValueCalls 259 exceeded limit of 200],
  '%s block options': [TOO BIG formatValueCalls 260 exceeded limit of 200],
  'Add Block After': [TOO BIG formatValueCalls 261 exceeded limit of 200],
  'Problem opening the video': [TOO BIG formatValueCalls 262 exceeded limit of 200],
  'Copied block': [TOO BIG formatValueCalls 263 exceeded limit of 200],
  'Double tap to move the block up': [TOO BIG formatValueCalls 264 exceeded limit of 200],
  '%s block. This block has invalid content': [TOO BIG formatValueCalls 265 exceeded limit of 200],
  'J.K. Rowling': [TOO BIG formatValueCalls 266 exceeded limit of 200],
  'Block settings': [TOO BIG formatValueCalls 267 exceeded limit of 200],
  'The way to get started is to quit talking and begin doing.': [TOO BIG formatValueCalls 268 exceeded limit of 200],
  'Link To': [TOO BIG formatValueCalls 269 exceeded limit of 200],
  Angle: [TOO BIG formatValueCalls 270 exceeded limit of 200],
  'Add Block Before': [TOO BIG formatValueCalls 271 exceeded limit of 200],
  'Search or type URL': [TOO BIG formatValueCalls 272 exceeded limit of 200],
  'Note: Column layout may vary between themes and screen sizes': [TOO BIG formatValueCalls 273 exceeded limit of 200],
  'Try a starter layout': [TOO BIG formatValueCalls 274 exceeded limit of 200],
  '%1$s. Current value is %2$s': [TOO BIG formatValueCalls 275 exceeded limit of 200],
  'My Document Setting Panel': [TOO BIG formatValueCalls 276 exceeded limit of 200],
  'My post status info': [TOO BIG formatValueCalls 277 exceeded limit of 200],
  'Juan Pérez': [TOO BIG formatValueCalls 278 exceeded limit of 200],
  'Email me: <a href="mailto:mail@example.com">mail@example.com</a>': [TOO BIG formatValueCalls 279 exceeded limit of 200],
  'My portfolio showcases various projects created throughout my career. See my contact information below and get in touch.': [TOO BIG formatValueCalls 280 exceeded limit of 200] }
07 - [Nov-10 22:10 STATS] 🔵 Tracked: editor_session_start, Properties: {"has_unsupported_blocks":"0","editor":"gutenberg","content_type":"new","startup_time_ms":4921,"session_id":"842b04a7-8244-4e48-8edb-e8eb43c83d29","post_type":"post","blog_type":"wpcom","editor_has_hw_disabled":"0","unsupported_blocks":[]}
08 - [Nov-10 22:10 API] ReactNativeStore: executeRequest
09 - [Nov-10 22:10 EDITOR] Using Toolbar without label prop is deprecated. Please use ToolbarGroup component instead. See: https://developer.wordpress.org/block-editor/components/toolbar/
10 - [Nov-10 22:10 API] Dispatching action: PostAction-UPDATE_POST
11 - [Nov-10 22:10 API] Dispatching action: ListAction-LIST_DATA_INVALIDATED
12 - [Nov-10 22:10 API] Dispatching action: ListAction-LIST_DATA_INVALIDATED
13 - [Nov-10 22:10 API] Dispatching action: PostAction-UPDATE_POST
14 - [Nov-10 22:10 API] Dispatching action: ListAction-LIST_DATA_INVALIDATED
15 - [Nov-10 22:10 API] Dispatching action: ListAction-LIST_DATA_INVALIDATED
16 - [Nov-10 22:10 API] Dispatching action: PostAction-UPDATE_POST
17 - [Nov-10 22:10 API] Dispatching action: ListAction-LIST_DATA_INVALIDATED
18 - [Nov-10 22:10 API] Dispatching action: ListAction-LIST_DATA_INVALIDATED
19 - [Nov-10 22:10 API] Dispatching action: PostAction-UPDATE_POST
20 - [Nov-10 22:10 API] Dispatching action: ListAction-LIST_DATA_INVALIDATED
21 - [Nov-10 22:10 API] Dispatching action: ListAction-LIST_DATA_INVALIDATED
22 - [Nov-10 22:10 API] Dispatching action: PostAction-UPDATE_POST
23 - [Nov-10 22:10 API] Dispatching action: ListAction-LIST_DATA_INVALIDATED
24 - [Nov-10 22:10 API] Dispatching action: ListAction-LIST_DATA_INVALIDATED
25 - [Nov-10 22:10 API] Dispatching action: PostAction-UPDATE_POST
26 - [Nov-10 22:10 API] Dispatching action: ListAction-LIST_DATA_INVALIDATED
27 - [Nov-10 22:10 API] Dispatching action: ListAction-LIST_DATA_INVALIDATED
28 - [Nov-10 22:10 API] Dispatching action: PostAction-UPDATE_POST
29 - [Nov-10 22:10 API] Dispatching action: ListAction-LIST_DATA_INVALIDATED
30 - [Nov-10 22:10 API] Dispatching action: ListAction-LIST_DATA_INVALIDATED
31 - [Nov-10 22:10 API] Dispatching action: PostAction-UPDATE_POST
32 - [Nov-10 22:10 API] Dispatching action: ListAction-LIST_DATA_INVALIDATED
33 - [Nov-10 22:10 API] Dispatching action: ListAction-LIST_DATA_INVALIDATED
34 - [Nov-10 22:10 STATS] 🔵 Tracked: editor_closed
35 - [Nov-10 22:10 STATS] 🔵 Tracked: media_picker_preview_opened, Properties: {"ext":"webp","is_video":false,"age_ms":356740004,"bytes":17682,"mime":"image\/webp","megapixels":0}
36 - [Nov-10 22:10 STATS] 🔵 Tracked: media_picker_recent_media_selected, Properties: {"ext":"webp","is_part_of_multiselection":false,"age_ms":356744979,"bytes":17682,"mime":"image\/webp","megapixels":0}
37 - [Nov-10 22:10 STATS] 🔵 Tracked: editor_opened, Properties: {"blog_id":159889361,"has_gutenberg_blocks":true,"post_type":"post","post_format":"standard","is_jetpack":false,"editor_has_hw_disabled":"0"}
38 - [Nov-10 22:10 STATS] 🔵 Tracked: editor_photo_added, Properties: {"ext":"webp","blog_id":159889361,"age_ms":356745019,"bytes":17682,"mime":"image\/webp","megapixels":0,"is_jetpack":false,"via":"device_library"}
39 - [Nov-10 22:10 API] Dispatching action: MediaAction-UPDATE_MEDIA
40 - [Nov-10 22:10 API] Dispatching action: ListAction-LIST_DATA_INVALIDATED
41 - [Nov-10 22:10 API] Dispatching action: ListAction-LIST_DATA_INVALIDATED
42 - [Nov-10 22:10 API] Dispatching action: PostAction-UPDATE_POST
43 - [Nov-10 22:10 API] Dispatching action: ListAction-LIST_DATA_INVALIDATED
44 - [Nov-10 22:10 MEDIA] MediaUploadHandler > Dispatching upload action for media with local id: 4 and path: /storage/emulated/0/Download/harbour-porpoise-640w.webp
45 - [Nov-10 22:10 API] Dispatching action: MediaAction-UPDATE_MEDIA
46 - [Nov-10 22:10 API] Dispatching action: MediaAction-UPLOAD_MEDIA
47 - [Nov-10 22:10 API] Dispatching action: ListAction-LIST_DATA_INVALIDATED
48 - [Nov-10 22:10 MEDIA] Media doesn't have required data: media must define a valid MIME type
49 - [Nov-10 22:10 API] Dispatching action: ListAction-LIST_DATA_INVALIDATED
50 - [Nov-10 22:10 API] Dispatching action: ListAction-LIST_DATA_INVALIDATED
51 - [Nov-10 22:10 MEDIA] MediaUploadHandler > Error uploading media: media must define a valid MIME type
52 - [Nov-10 22:10 API] Dispatching action: MediaAction-UPDATE_MEDIA
53 - [Nov-10 22:10 API] Dispatching action: ListAction-LIST_DATA_INVALIDATED
54 - [Nov-10 22:10 API] Dispatching action: ListAction-LIST_DATA_INVALIDATED
55 - [Nov-10 22:10 STATS] 🔵 Tracked: media_service_upload_response_error, Properties: {"ext":"webp","age_ms":356745192,"bytes":17682,"mime":"image\/webp","megapixels":0,"error_type":"MALFORMED_MEDIA_ARG"}
56 - [Nov-10 22:10 STATS] 🔵 Tracked: media_service_upload_started, Properties: {"ext":"webp","age_ms":356745198,"bytes":17682,"mime":"image\/webp","megapixels":0}
57 - [Nov-10 22:10 MEDIA] MediaUploadHandler > No more media items to upload. Skipping this request.
58 - [Nov-10 22:10 MEDIA] MediaUploadHandler > Completed
59 - [Nov-10 22:10 MAIN] UploadService > Media upload failed for post 101 : MALFORMED_MEDIA_ARG: media must define a valid MIME type
60 - [Nov-10 22:10 POSTS] updateNotificationErrorForPost: There was an error uploading the media in this post: Media must define a valid MIME type.
61 - [Nov-10 22:10 STATS] 🔵 Tracked: notification_shown, Properties: {"notification_type":"post_upload_error"}
62 - [Nov-10 22:10 API] Dispatching action: ListAction-LIST_DATA_INVALIDATED
63 - [Nov-10 22:10 API] Dispatching action: PostAction-UPDATE_POST
64 - [Nov-10 22:10 API] Dispatching action: UploadAction-CANCEL_POST
65 - [Nov-10 22:10 API] Dispatching action: ListAction-LIST_DATA_INVALIDATED
66 - [Nov-10 22:10 POSTS] updateNotificationErrorForPost: There was an error uploading the media in this page: We couldn't complete this action..
67 - [Nov-10 22:10 STATS] 🔵 Tracked: notification_shown, Properties: {"notification_type":"post_upload_error"}
68 - [Nov-10 22:10 API] Dispatching action: UploadAction-CANCEL_POST
69 - [Nov-10 22:10 API] Dispatching action: ListAction-LIST_DATA_INVALIDATED
70 - [Nov-10 22:10 STATS] 🔵 Tracked: editor_upload_media_failed, Properties: {"ext":"webp","age_ms":356745237,"bytes":17682,"mime":"image\/webp","megapixels":0,"error_type":"MALFORMED_MEDIA_ARG"}
71 - [Nov-10 22:11 API] Dispatching action: PostAction-UPDATE_POST
72 - [Nov-10 22:11 API] Dispatching action: ListAction-LIST_DATA_INVALIDATED
73 - [Nov-10 22:11 STATS] 🔵 Tracked: editor_draft_saved, Properties: {"blog_id":159889361,"post_id":0,"has_gutenberg_blocks":true,"post_type":"post","post_format":"standard","is_jetpack":false}
74 - [Nov-10 22:11 EDITOR] Post had no unsaved changes when exiting the editor.
75 - [Nov-10 22:11 API] Dispatching action: ListAction-LIST_DATA_INVALIDATED
76 - [Nov-10 22:11 STATS] 🔵 Tracked: editor_closed
77 - [Nov-10 22:11 UTILS] trackLastActivity, activityId: Post List
78 - [Nov-10 22:11 UTILS] SnackbarSequencer > New item added
79 - [Nov-10 22:11 UTILS] SnackbarSequencer > invoking start()
80 - [Nov-10 22:11 UTILS] SnackbarSequencer > prepareSnackBar message [2 files not uploaded
There was an error uploading the media in this page: We couldn't complete this action..]
81 - [Nov-10 22:11 UTILS] SnackbarSequencer > before delay
82 - [Nov-10 22:11 UTILS] SnackbarSequencer > New item added
83 - [Nov-10 22:11 STATS] 🔵 Tracked: editor_session_end, Properties: {"has_unsupported_blocks":"0","editor":"gutenberg","content_type":"new","session_id":"842b04a7-8244-4e48-8edb-e8eb43c83d29","post_type":"post","blog_type":"wpcom","editor_has_hw_disabled":"0","outcome":"save"}
84 - [Nov-10 22:11 UTILS] trackLastActivity, activityId: My Site
85 - [Nov-10 22:11 API] Dispatching action: AccountAction-FETCH_ACCOUNT
86 - [Nov-10 22:11 PROFILING] Visual Editor Startup: begin
87 - [Nov-10 22:11 PROFILING] Visual Editor Startup: 0 ms, EditorFragment.onCreate
88 - [Nov-10 22:11 PROFILING] Visual Editor Startup: 83605 ms, WPMainActivity.onResume
89 - [Nov-10 22:11 PROFILING] Visual Editor Startup: end, 83605 ms
90 - [Nov-10 22:11 API] WhatsNewStore: fetchWhatsNew
91 - [Nov-10 22:11 API] Dispatching action: AccountAction-FETCHED_ACCOUNT
92 - [Nov-10 22:11 UTILS] SnackbarSequencer > after delay
93 - [Nov-10 22:11 UTILS] SnackbarSequencer > item removed from the queue
94 - [Nov-10 22:11 UTILS] SnackbarSequencer > start context was not alive
95 - [Nov-10 22:11 UTILS] SnackbarSequencer > item removed from the queue
96 - [Nov-10 22:11 UTILS] SnackbarSequencer > finishing start()
97 - [Nov-10 22:11 STATS] 🔵 Tracked: me_tab_accessed
98 - [Nov-10 22:11 STATS] 🔵 Tracked: support_opened, Properties: {"origin":"ME_SCREEN_HELP"}
99 - [Nov-10 22:11 UTILS] trackLastActivity, activityId: Help Screen
```
</details>

**Comment by designsimply** [comment]
Also see https://github.com/wordpress-mobile/WordPress-Android/issues/2885.

**Comment by reginabally** [comment]
Another report in 3478657-zen. Still asking for the device information.

> I noticed the latest version from play store still has issue with app getting stuck trying to upload image if choosing a .webp file (Google image format). Chrome saves images in this format on some sites to reduce size and dara usage.

> You get error in app and option to retry but if you remove it there is a Android notification that shows it still trying and can't swipe to clear it. You have to go to draft and save post.

**Comment by dromero20** [comment]
The user got back to us in 3478657-zen and shared these details:

```
Android v10
Model - samsung / SM-N960W
```

**Comment by reginabally** [comment]
Reported in an app review:

> Still has issue with app getting stuck trying to upload image if choosing a .webp file (Google image format).

Date and time of the review: Nov 10, 2020, 22:37
Device:  Samsung Galaxy Note9
OS: Android 10 (SDK 29)

**Comment by planarvoid** [comment]
thanks for reporting this @designsimply ! Could you please double check this with the new media picker (which will be coming out in the next release)? We've implemented a solution to filter out webp images. Thanks!

**Comment by hypest** [comment]
Not sure, is this ticket addressed at this point? Should we close it?

**Comment by designsimply** [comment]
@planarvoid @hypest this issue is still valid. I tested with 16.3-rc-3 and The same problem is still happening. Since the ask to retest is from 28 days ago and 16.2 was released 9 days ago, I think it should be working in the 16.3 beta, yes?

Video: [3m30s](https://cloudup.com/cYX-1VILsPr)
<sup>Tested with WPAndroid 16.3-rc-3 on Pixel 4 Android 10.</sup> 

Should this issue be moved to the gutenberg-mobile repo? Why or why not? (asking for my own knowledge 😊)

**Comment by hypest** [comment]
Aha, I see the flow you used there @designsimply. Looks like you tried it via another app and Google Photos did allow for selecting the webp image. Our own image picker and the Android picker doesn't allow selecting the webp ones.

So, this seems like a subcase of the overall flow. @planarvoid , do you think there's a way to limit any app via the picker, or at least Google Photos?

**Comment by designsimply** [comment]
Or 😁😁😁 what about adding support for webp images?

**Comment by hypest** [comment]
Pinging @frosty here since y'all recently worked on a media picker consolidation project: is there any context around where we are in terms of supporting webp and any particular reason we kept it as unsupported in that recent project?

BTW, there's [this ticket open about webp support in the apps](https://github.com/wordpress-mobile/WordPress-Android/issues/2885).

**Comment by frosty** [comment]
Thanks for the ping. As far as I'm aware, webp still is not supported by the backend – there was [this post](https://wordpress.com/blog/2015/12/04/webp-images-support/) many years ago about webp support, but I think that was about _serving_ webp images. This [more recent forum post](https://wordpress.com/forums/topic/bring-webp-images-on-wordpress-com-sites/) mentions that webp isn't allowed as an upload format.

**Comment by designsimply** [comment]
Oh! Thank you for the update. In that case, we definitely shouldn't allow uploading webp images from Gutenberg Mobile and we should show a proper error when someone tries to.

<sup>(I had skimmed internal reference p4TIVU-9se-p2 about enabling webp but now I realize it was a different context.)</sup>

For comparison, if you try to upload a webp image using Calypso Gutenberg it replies with the following error:

> Sorry, this file type is not permitted for security reasons.

![image](https://user-images.githubusercontent.com/1119271/102289162-3c0b0280-3efb-11eb-9589-c4d7307ed77a.png)

**Comment by frosty** [comment]
Thanks for clarifying, @designsimply.

As @planarvoid is AFK until January, pinging @develric – do you know if there's a way we can prevent webp files from being selected in the system picker? (see [this video](https://cloudup.com/cYX-1VILsPr) for an example)

**Comment by develric** [comment]
Hey 👋 . For what I remember the expected behaviour currently implemented is:
- not present not supported media types in the app mediapicker; but you can always go to the system picker from this icon
<p align=center><image src="https://user-images.githubusercontent.com/47797566/102609203-62af8000-412b-11eb-8a55-26b08b681af2.png" width=300/></p>

- Once you are in the system picker, we do not have full control both on how it looks like and options it has since it depends also from the Android flavor customization that the manufacturer can apply. What has been done is to gray out not supported types. And I see if you go into Downloads from the left menu (as @designsimply did at some point in the video) you get the above behaviour (that is webp image grayed out)

| ![image](https://user-images.githubusercontent.com/47797566/102609768-5bd53d00-412c-11eb-9ec6-6d20edee9f3f.png) | ![image](https://user-images.githubusercontent.com/47797566/102609868-790a0b80-412c-11eb-8f0c-0ef92cd248a8.png) |
|---|---|

- BUT it seems that when you access the image in the system picker going to Photos or Gallery the gray out filtering is not applied so it creates the inconsistent behaviour

| ![image](https://user-images.githubusercontent.com/47797566/102610251-267d1f00-412d-11eb-9210-2e8abd99b1db.png) | ![image](https://user-images.githubusercontent.com/47797566/102610346-59271780-412d-11eb-9ac5-7c492c42c23a.png) |
|---|---|

Didn't have the occasion to look at what degree we can have the grayed out behaviour applied to the Photos/Gallery path (even if my gut feeling is we have not much since we navigate there from the system picker, but better check 😄 ). 
I would:
- try to make the grayed behaviour for not supported formats consistent also for photos/gallery (I can look at it a bit further next week before my AFK and eventually report here or in a dedicated issue what I find)
- If we cannot cover the above (or we are not happy with it anyway) I guess we should consider that it's still possible to attempt an upload for not supported formats from some path and improve the error we show in that case (tbh the message improvement is maybe worth regardless, in case we just miss any additional path that can lead to this 😄 )

Let me know wdyt 🙇  .

**Comment by develric** [comment]
Quick follow up to say that AFAIU I need to confirm the above, that is:
- as long as we stay in the system picker we already specify the valid mime types (`EXTRA_MIME_TYPES` in the Intent); so that the relevant media are in this way listed but grayed out (and intentionally not possible to select them)
- in the system picker there can be additional apps like gallery or google photos started up from the system picker and as of now I could not find a way to force them to use the same list of valid mime types with which we started up the system picker (good to get ideas here in case I'm missing anything 🙇‍♂️ ).

I would say the best we can do is to improve the error message and how we present it to user. While looking into this I saw that we currently report the error in the dialog that appears tapping on the failed image upload block (even if this remains pretty hidden tbh).

<p align=center><image src="https://user-images.githubusercontent.com/47797566/102939109-e6f85f00-44ad-11eb-9aa5-6fe6387c8cb7.png" width=300/></p>

Also this remembered me of another discussion [here](https://github.com/wordpress-mobile/WordPress-Android/issues/7103) that slipped through the cracks ( 🙃  ) but is super related and drafts some highlights ([here](https://github.com/wordpress-mobile/WordPress-Android/issues/7103#issuecomment-689695617) and maybe more [here](https://github.com/wordpress-mobile/WordPress-Android/issues/7103#issuecomment-690354399)). I'm going to be AFK until new year but if nobody beats me on covering this (and with it, the #7103) I think I can work on it (I would say most probably on WK2). cc @designsimply

**Comment by planarvoid** [comment]
Thanks for the investigation @develric . I'd even consider changing the error text "Media must define a valid MIME type" - it's not really an invalid type, our server just doesn't support it.

**Comment by designsimply** [comment]
Maybe something closer to the Calypso wording? Simplified: "This file type is not allowed." 

I think it would be more user-friendly to leave out "MIME type". 😬 😊

**Comment by AmandaRiu** [comment]
Tested on an emulator running Android 11 and this is still an issue when selecting a webp image via Photos. Looking at the notes on this ticket it seems this is already known and the next step is to figure out what the error message should say. 

<img src="https://user-images.githubusercontent.com/5810477/113064781-b4819080-9185-11eb-959c-1cacf308b643.png" width="300"/>


Pinging @planarvoid  as it looks like the last question on this ticket was directed to him.

**Comment by planarvoid** [comment]
I think this could be handled in Groundskeeping, wdyt @AmandaRiu ?

**Comment by rezzap** [comment]
There's another user reporting not being able to upload .webp file types in 4015797-zen
