### ISSUE TITLE
IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/WordPress-Android#14763]
**Sentry Url**: https://sentry.io/share/issue/75d4493fe7f5459ea340929e3fc6aecf/
**User Count**: 205
**Count**: 3016
**First Release**: 17.0 (1023)
**First Seen**: Apr 8, 2021 3:27:28 AM UTC
**Last Seen**: Jun 2, 2021 10:55:27 AM UTC
**24 Hours**: 269
**30 Days**: 2836

<details><summary><strong>Stacktrace</strong></summary>

```
java.lang.IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
 ViewHolder 1:CommentSubHeaderViewHolder{31e3e76 position=10 id=0, oldPos=-1, pLpos:-1 not recyclable(1)} 
 View Holder 2:CommentSubHeaderViewHolder{6071f4 position=7 id=0, oldPos=-1, pLpos:-1} androidx.recyclerview.widget.RecyclerView{f82b0e4 VFED..... ......ID 0,0-1080,1676 #3}, adapter:org.wordpress.android.ui.comments.CommentAdapter@e2f94d, layout:androidx.recyclerview.widget.LinearLayoutManager@727cc02, context:org.wordpress.android.ui.comments.CommentsActivity@406414c
    at androidx.recyclerview.widget.RecyclerView.handleMissingPreInfoForChangeError(RecyclerView.java:4268)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:4192)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3862)
    at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
    at android.view.View.layout(View.java:22844)
    at android.view.ViewGroup.layout(ViewGroup.java:6389)
    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
    at android.view.View.layout(View.java:22844)
    at android.view.ViewGroup.layout(ViewGroup.java:6389)
    at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:689)
    at android.view.View.layout(View.java:22844)
    at android.view.ViewGroup.layout(ViewGroup.java:6389)
    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
    at android.view.View.layout(View.java:22844)
    at android.view.ViewGroup.layout(ViewGroup.java:6389)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:22844)
    at android.view.ViewGroup.layout(ViewGroup.java:6389)
    at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:9587)
    at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1685)
    at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
    at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
    at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
    at android.view.View.layout(View.java:22844)
    at android.view.ViewGroup.layout(ViewGroup.java:6389)
    at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:527)
    at android.view.View.layout(View.java:22844)
    at android.view.ViewGroup.layout(ViewGroup.java:6389)
    at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
    at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
    at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1996)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
    at android.view.View.layout(View.java:22844)
    at android.view.ViewGroup.layout(ViewGroup.java:6389)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:22844)
    at android.view.ViewGroup.layout(ViewGroup.java:6389)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:22844)
    at android.view.ViewGroup.layout(ViewGroup.java:6389)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:22844)
    at android.view.ViewGroup.layout(ViewGroup.java:6389)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
    at android.view.View.layout(View.java:22844)
    at android.view.ViewGroup.layout(ViewGroup.java:6389)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at com.android.internal.policy.DecorView.onLayout(DecorView.java:784)
    at android.view.View.layout(View.java:22844)
    at android.view.ViewGroup.layout(ViewGroup.java:6389)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3475)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2943)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8177)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
    at android.view.Choreographer.doCallbacks(Choreographer.java:796)
    at android.view.Choreographer.doFrame(Choreographer.java:731)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7660)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

</details>

**Comment by fluiddot** [comment]
Looks like this began to happen in version `17.0`, I checked the release notes for that version ([code reference](https://github.com/wordpress-mobile/WordPress-Android/blob/d19d7672b72ea5b08c138f635025ae9f3cc2c687/RELEASE-NOTES.txt#L26)) and the comment list was updated in this [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/14417).

@khaykov, as the author of the PR, do you have any clue about this issue? Thanks 🙇 !

**Comment by khaykov** [comment]
@fluiddot Yep, looks like this issue is with the missing comment timestamps on self-hosted sites. Thanks for the report! Working on the fix 👍

**Comment by fluiddot** [comment]
> @fluiddot Yep, looks like this issue is with the missing comment timestamps on self-hosted sites. Thanks for the report! Working on the fix 👍

Awesome! Thank you so much @khaykov for addressing it so quickly 🙇 !

**Comment by fluiddot** [comment]
The Sentry issue has been marked resolved in the next release.

**Comment by AliSoftware** [comment]
The Sentry issue reappeared and is still happening in 17.8 – which was released to end users on Jul 26 so more than one release after this issue was closed: https://sentry.io/share/issue/75d4493fe7f5459ea340929e3fc6aecf/

@zwarm (as CTrO): not sure if we're supposed to reopen the issue or create a new one in those cases? Reopening this one for now but feel free to re-close it and open a new one instead.

**Comment by zwarm** [comment]
@AliSoftware  
>  not sure if we're supposed to reopen the issue or create a new one in those cases?  

I'm not sure either. 🤷 , but if I look at Sentry - the errors point to two different parts of the code (similar issue)
I'm going to create a new ticket and re-close this one.
