### ISSUE TITLE
Land in the editor: exclude existing sites from the treatment

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-Android#15968]
### Expected behavior
The users should **not** [land to the home page editor](https://github.com/wordpress-mobile/WordPress-Android/pull/15627) when they select an existing site from the login epilogue view

### Actual behavior
The users [land to the home page editor](https://github.com/wordpress-mobile/WordPress-Android/pull/15627) when they select an existing site from the login epilogue view

### Steps to reproduce the behavior
1. Login to the app with a user that has the Treatment variation assigned (check https://github.com/wordpress-mobile/WordPress-Android/pull/15627 for instructions on this) and at least one existing site
2. Select site from the login epilogue view
3. *Notice* that you see the home page editor

**Comment by mkevins** [comment]
I wonder, is this resolved now that we have [removed the experiment](https://github.com/wordpress-mobile/WordPress-Android/pull/16145), or should this also be addressed for the flow behind the feature flag?

**Comment by antonis** [comment]
This should be still reproducible for the flow behind the feature flag. Let's keep it on our Backlog to tackle when we revisit this feature.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
