### ISSUE TITLE
Crash report 4.5.1 - NPE adding toolbar in NotificationsSettingsFragment

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#3235]
```
java.lang.NullPointerException
       at org.wordpress.android.ui.prefs.notifications.NotificationsSettingsFragment.addToolbarToPreferenceScreen(NotificationsSettingsFragment.java:360)
       at org.wordpress.android.ui.prefs.notifications.NotificationsSettingsFragment.onPreferenceTreeClick(NotificationsSettingsFragment.java:350)
       at android.preference.Preference.performClick(Preference.java:949)
       at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:202)
       at android.widget.AdapterView.performItemClick(AdapterView.java:292)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1173)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:2701)
       at android.widget.AbsListView$1.run(AbsListView.java:3453)
       at android.os.Handler.handleCallback(Handler.java:605)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4514)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by tonyr59h** [comment]
Addressed in #3240, closing.

**Comment by roundhill** [comment]
Still happening on 4.5.2, looks like an issue w/ only Android 4.0.X
