### ISSUE TITLE
Notification Remains Unread After Opening From System Notification

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#5061]
### Expected
Notifications are marked as read when returning to the Notification tab after opening a system notification.

### Observed
Notifications remain unread when returning to the Notification tab after opening a system notification until the tab is refreshed manually or the notification is opened from the Notification tab.

### Reproduced
***Refresh***
1. Open a system notification from the WordPress app.
2. Tap the back arrow or back button.
3. Notice the notification is still unread (i.e. light blue background).
4. Swipe down to refresh the ***Notifications*** tab.
5. Notice the notification is now read (i.e. white background).

***Reread***
1. Open a system notification from the WordPress app.
2. Tap the back arrow or back button.
3. Notice the notification is still unread (i.e. light blue background).
4. Tap the notification from the list.
5. Tap the back arrow or back button.
6. Notice the notification is now read (i.e. white background).

##### Tested
Google Pixel on Android 7.1.1 with WordPress 6.5

**Comment by daniloercoli** [comment]
Can't reproduce this issue in `develop`, but it's probably due to some race conditions. Keeping an eye on this the next few days, also pinging @mzorz, maybe he can reproduce it.

**Comment by mzorz** [comment]
I can't reproduce this issue either - tried on a couple emulators and on the Pixel as well. 
@theck13 can you check if it's still happening and if yes, which kind of notification was that and any other info that might be useful to try reproduce on our side please? thanks in advance

**Comment by mzorz** [comment]
Managed to repro by having the app in the background (deleted from the recent app list) when the notification comes in and the user opens it (thank you @theck13 !)

**Comment by daniloercoli** [comment]
Addressed in #5074

**Comment by theck13** [comment]
I'm getting some similar behavior to the ***Refresh*** steps above, but the read notification now becomes unread and refreshing the list.  I can't reproduce this on a stock emulator, but I've reproduced this multiple times on a Google Pixel 3 on Android 9.0 with WordPress 11.6.

### Reproduced
#### Refresh
0. Remove WordPress from recent apps on overview screen.
1. Open system notification from WordPress app.
2. Tap back arrow or back button.
3. Notice notification is still _read_ (i.e. white background).
4. Swipe down to refresh ***Notifications*** tab.
5. Notice the notification is now _unread_ (i.e. gray background).

**Comment by hypest** [comment]
Issue still happens for me. The list item in the notifications tab turns unread after I have opened the particular notification from Android's status bar.

What happens in the GIF:
1. I open a notification from Android's status bar
2. App opens in the post comment the notification is about
3. I tap "Back" and app returns to the notifications list
4. Most recent notification is shown as "read" as it should
5. Moments later, the notification item turns blueish, showing as "unread" 💥

![notif-turns-unread](https://user-images.githubusercontent.com/1032913/75138370-bb241580-56f2-11ea-936d-ef5d94f731b8.gif)

**Comment by develric** [comment]
Just confirming that this seems to be still valid to me with current develop (at this point in [history](https://github.com/wordpress-mobile/WordPress-Android/tree/a860d8b29eb097aed016d28092021c4fa756a2c4)). 

Getting the same effect as hypest [here](https://github.com/wordpress-mobile/WordPress-Android/issues/5061#issuecomment-590218247) and only if the app was in background initially (as for Mario comment [here](https://github.com/wordpress-mobile/WordPress-Android/issues/5061#issuecomment-275703722))

Tested on Pixel 3 Emu API 30

**Comment by theck13** [comment]
Some work was started fixing this issue in https://github.com/wordpress-mobile/WordPress-Android/tree/notifications-mark-unread, but it was never finished.

**Comment by thabotswana** [comment]
Another report here: 4043365-zen

Mobile device: Galaxy A70
OS: Android 11
Wordpress app version: 17.4

**Comment by ravishanker** [comment]
Tested this on v18.0 and 18.1,  didn't observe the behavior mentioned above.  Please do reopen this if it is noticed again with detailed steps

**Comment by thehenrybyrd** [comment]
I'm still seeing the notification go back to "unread" (blue) after it is marked "read" for a moment:

https://user-images.githubusercontent.com/15107387/132819410-3ca0b74a-f8e6-4108-9639-2f6cb8016b93.mp4

As seen in the recording, the notification does initially get marked as read, and no longer has a blue background. However, after waiting a moment, it goes back to unread.

**Comment by ashiagr** [comment]
I was able to reproduce the issue by following these steps:

1. Send at least two notifications.
2. Click on a notification in the notifications tray (since there are two notifications, the `notifications list` screen is shown instead of the `notification details` screen).
3. Quickly tap that notification from the `notifications list` screen to go to the `notification details` screen.
4. Return to the `notifications list` screen.
5. Wait for a few seconds.
6. Notice that the notification is marked `read` quickly followed by `unread` status.

It seems that refresh happens from two sources simultaneously: local DB and remote server. A race condition is reached if the [refresh request from the remote server completes](https://github.com/wordpress-mobile/WordPress-Android/blob/378027dcaae3774bb6650caecc2f72a0a82aead2/WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragmentPage.kt#L436) later than the [local DB refresh](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragmentPage.kt#L429).

https://user-images.githubusercontent.com/1405144/147750466-c927e024-8694-43ff-ab2c-1ce880f8776d.mp4

**Comment by antonis** [comment]
Closing the issue since the notification is marked as read with the latest implementation when you return to the notifications list.

https://github.com/wordpress-mobile/WordPress-Android/assets/304044/40b31105-9afa-43be-8352-0d9cf837fff1
