### ISSUE TITLE
Google Login/Signup: Newly added Google account does not appear in account list

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#8053]
When authenticating via Google, its possible the desired Google account is not already present on the user's device.  In this case the user can tap the option to add an account on the Google account selection dialog.  After adding the Google account to the device, the dialog is not immediately updated to show the account in the list.

To reproduce:
- While logged out of the WordPress app, confirm that the Google account you wish to authenticate with is not currently present on the Android device.
- Open the WordPress app and enter the Google login flow.
- When prompted to choose a Google account to use for authentication, tap the option to add a new account.  Its the "None of the Above" button.
- Follow the flow to add a Google account to the device. 
- When finished, note that the newly added account is not present in the account dialog.
- Tap in the background to dismiss the dialog.
- Choose the Google login option again. 
- Confirm that the newly added Google account is now present.

**Comment by theck13** [comment]
It looks like this is a bug in the Google Play Services app.  That means we can't fix it, but [a fix was released by Google a week ago and is in a staged rollout across all Android devices](https://github.com/googlesamples/google-services/issues/358#issuecomment-403612044).  In other words, we just have to wait for the Google Play Services app update and it should be fixed.

**Comment by aerych** [comment]
Thanks for investigating!  Since Google's fixing let's just close this one.

**Comment by kashifo** [comment]
Hey, this still issue is still occurring in Android devices.

**Comment by aerych** [comment]
@kashifo Can you let us know the version of Android and devices on which you're seeing the issue?
